### ISSUE TITLE
Disk usage: remove docs and specs from packaged gem?

### ISSUE THREAD

**Issue by Fryguy** [xlab-si/intersight-sdk-ruby#17]
This gem is a very large gem, taking up about 169MB of disk space.  This is the largest gem we have in the ManageIQ projects in terms of disk space (locally, the next largest gem is azure_mgmt_network-0.26.1 at about 140MB). #11 and #16 made some good strides towards that. Prior to that the disk size was 189MB, so those 2 PRs saved 20MB of disk space.

However, it's still pretty large.  Here is the directory breakdown:

```
93172	lib
41108	docs
36992	spec
1332	README.md
12	LICENSE
4	Rakefile
4	Gemfile
```

My suggestion is to remove `docs` and `spec` from the package as they aren't needed by end users.  This will drop the disk space usage by 76MB, dropping the gem size to 93MB (~45% reduction).

@zitnik @agrare Would like your thoughts here.

**Comment by Fryguy** [comment]
Weird - strangely `spec` is _already_ in the exclude list, but for some reason I have it locally on disk in 0.1.4

**Comment by zitnik** [comment]
The reason for `spec` being included is the `test_files` definition - which I think we can safely remove.
`docs` are not needed either IMO, I've always browsed docs here on github when needed.

I agree with the suggestion, thanks!

**Comment by Fryguy** [comment]
Ah ok, the spec thing makes sense - I'll update my PR.

**Comment by Fryguy** [comment]
I decided to just make a separate PR for removing spec, so there are 2 PRs that together fix this and remove 76MB from the deliverable: #18 and #19

**Comment by zitnik** [comment]
Thanks @Fryguy
I also just pushed a new gem release with these changes.
